# Generated by Django 5.2.1 on 2025-05-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('anxious', '😟 Anxious'), ('neutral', '😐 Neutral')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
